#copy()
original_dict={'a':1,'b':2,'c':3,'g':5,'h':10}
new_dict=original_dict.copy()
print(new_dict)
#items
items=new_dict.items()
print(items)
#keys()
keys=new_dict.keys()
print(keys)
#values
values=new_dict.values()
print(values)
#pop(key)
value=new_dict.pop('b')
print(values)
print(new_dict)
#popitems()
items=new_dict.popitem()
print(items)
print(new_dict)
#setdefault
value=new_dict.setdefault('d',0)
print(value)
print(new_dict)
#update
dict1={'e':3,'r':5}
dict2={'o':4,'t':5}
dict1.update(dict2)
print(dict1)
